### ISSUE TITLE
Signs Section in Locale_EN.yml

### ISSUE THREAD

**Issue by iblacksheep** [Zrips/TryMe#10]
My Locale_EN.yml file generates without the necessary information under the Signs heading to create toplist signs. I've tried regenerating the file, and it regenerates that way. I am up-to-date on the version (7.0.0.3 for TryMe and 1.2.0.2 for CMILib). I've looked for a reference file and asked about it in the community discord. Not sure why it is generating this way, but it's rendered top signs useless. Please advise?

**Comment by FourNineRugz** [comment]
confirmed this doesnt work for me as well

**Comment by Zrips** [comment]
Todays update will resolve this issue

**Comment by iblacksheep** [comment]
Thank you!
