### ISSUE TITLE
[Feature Request] Mine "x" things first.

### ISSUE THREAD

**Issue by mrfloris** [Zrips/TryMe#11]
It would be so cool if this plugin could get a bit more modern and do a bit more than chat msgs. 

For example: "Be the first to mine a cobblestone"
For example: "Be the first to mine deepslate lapis lazule ore"
For example: "Be the first to mine 3x smooth quartz block"
and then publicly announce the winner, and run a console command as reward (so we can use like /cmi kit ..)

**Comment by Zrips** [comment]
Next update

**Comment by mrfloris** [comment]
Thank you!
