### ISSUE TITLE
[Feature Request] Kill angry / friendly mob type

### ISSUE THREAD

**Issue by mrfloris** [Zrips/TryMe#12]
It would be so cool if this plugin could get a bit more modern and do a bit more than chat msgs. 

For example: "Be the first to kill an angry mob: baby zombie"
For example: "Be the first to kill a friendly mob: donkey"
For example: "Be the first to kill 4 different angry mobs"
and then publicly announce the winner, and run a console command as reward (so we can use like /cmi kit ..)

**Comment by Zrips** [comment]
Next update
