### ISSUE TITLE
[Feature Request] Item Consuming support

### ISSUE THREAD

**Issue by mrfloris** [Zrips/TryMe#14]
It would be so cool if this plugin could get a bit more modern and do a bit more than chat msgs. 

For example: "Be the first to eat an enchanted golden apple"
For example: "Be the first to eat suspicious stew"
For example: "Be the first to eat raw porkchop"
and then publicly announce the winner, and run a console command as reward (so we can use like /cmi kit ..)

**Comment by Zrips** [comment]
Next update

**Comment by mrfloris** [comment]
Awesome news, can't wait to play with it.
