### ISSUE TITLE
hangman is bugged

### ISSUE THREAD

**Issue by dan28000** [Zrips/TryMe#16]
![image](https://user-images.githubusercontent.com/84990628/194772641-3c8134dd-9234-42e4-96be-34e06b54724b.png)
![image](https://user-images.githubusercontent.com/84990628/194775364-4ec1e3ae-b07a-4017-a545-d6a1aa321f8c.png)

pretty sure that "e" universaly = win
not sure if it's my setup but it happens kinda random i feel

**Comment by Zrips** [comment]
Should be working with latest builds
