### ISSUE TITLE
New modes not giving rewards

### ISSUE THREAD

**Issue by RedShaunia** [Zrips/TryMe#18]
break/eat/kill is not giving rewards. I've regenerated all the configs in case that was the issue. No go.
Also made those modes false in the config since they do not appear to be working, reloaded, and they are still coming up in chat. Double checked config they are indeed false. (edit) Took server restart to make the modes not come up)
Running TryMe Version 7.1.0.2 on 1.19.2 Paper #270 and CMILib 1.2.3.7

**Comment by Teleriann** [comment]
+1 I have same issue. All new modes are set to false, like on screen and when i start /amode, it is still there. Also when this type of "question" starts, it cant be completed. For example, "kill a zombie", when player kill zombie nothing happens.

![image](https://user-images.githubusercontent.com/71602218/203060959-f859cb2c-3aa1-4e44-854f-1cef015d13e4.png)

**Comment by ACluco1** [comment]
I have the same issue (7.1.0.5 on Purpur-1886 - 1.19.3)

**Comment by bobhenl** [comment]
Me as well. Can it be looked on @Zrips please?

**Comment by Zrips** [comment]
Will fix it with next update tomorrow
