### ISSUE TITLE
/tryme top does not return any results

### ISSUE THREAD

**Issue by FourNineRugz** [Zrips/TryMe#21]
![image](https://user-images.githubusercontent.com/17154368/204063830-f31364ac-65f5-4c9f-a1c0-a5bd185938fa.png)

Picture. Leaderboard does not work no matter if it's a hologram, sign, or typing the command.

**Comment by Zrips** [comment]
will fix. In general amode will not have top list as there is no point in combining different game modes and show their timers as one mode is not equal to another one and results would be quite useless anyways.
