### ISSUE TITLE
Incorrect output of the correct answer.

### ISSUE THREAD

**Issue by samparotony228** [Zrips/TryMe#22]
**Problem**:
1. The plugin runs without errors. But when the response times out and the plugin reports what the correct response was, it displays "null" instead of the correct response.

2. When the plugin asks a question, I answer it correctly via /answ [answer], but it tells me that I did not answer correctly, although I answer 100% correctly..
_(It seems to me that error 2 arose directly due to error 1. But that's just my guess...)_

**Additional Information**:
Server: git-Purpur-1858 (MC: 1.19.2) lasted version.
CMILib version: 1.2.4.1
TryMe version: 7.1.0.4

**Comment by Zrips** [comment]
Should be fixed with new release

**Comment by samparotony228** [comment]
> Should be fixed with new release

After the update everything works.
